### ISSUE TITLE
Erroneous Class IDs (-2147483648) in Relion 4

### ISSUE THREAD

**Issue by davidheisenberg** [3dem/relion#916] opened 2022-09-21 00:49 UTC
Hello all,

I am performing ab initio model generation in Relion 4 on pseudo-subtomograms but I am getting something weird that I can't figure out. 

Many of my particles get a class number "-2147483648" instead of the usual 1, 2, 3, etc. (Perhaps worth noting, for the first 40 iterations, all particles had sensible class numbers, but after that, a variable number of particles would have the strange class number).

I have tried it using both a slightly older version of Relion 4, as well as a freshly installed one (4.0-beta-2-commit-b5a555), and in both cases I get the strange class number. Also, it seems that relion_refine starts writing out the wrong class number after an automatic increase of the healpix in the ab initio run (going from healpix 2 to 3 at iteration 40).

Apparently, a colleague in my lab found a work-around whereby if --sigma_ang (local search) is used for the first few iterations of the higher healpix iterations, and then --sigma_ang is reduced to 0 (global search), the class numbers are written out normally. I did try this for my case and it seemed to work (all particles written out with correct Class IDs).

**Environment:**
 - OS: Ubuntu 20.04 LTS
 - MPI runtime: N/A (VDAM)
 - RELION version: 4.0-beta-2-commit-b5a555 and 4.0-beta-2-commit-e55b9a
 - Memory: 504 GB
 - GPU: 4x GTX 3080Ti

**Dataset:**
 - Box size: 56 px
 - Pixel size: 4.269 Å/px
 - Number of particles: 69,626
 - Description: Small globular protein (100 A in width)

**Job options:**
 - Type of job: Relion ab initio
 - Number of MPI processes: N/A (VDAM)
 - Number of threads: 96
 - Full command (see `note.txt` in the job directory):

`which relion_refine` --o InitialModel/all_bin3_VDAM_R3/run --iter 100 --grad --denovo_3dref  --i Select/all_bin3_VDAM_R3/particles.star --ctf --K 8 --sym C1  --flatten_solvent  --zero_mask  --dont_combine_weights_via_disc --pool 3 --pad 1  --skip_gridding  --particle_diameter 220 --oversampling 1  --healpix_order 1  --offset_range 6  --offset_step 2 --auto_sampling  --tau2_fudge 1 --j 36 --gpu ""

Error message:

No error message was given, the main problem is the Class ID is wrong in the data.star.

**Comment by biochem-fan** [comment] 2022-09-21 01:06
This is indeed concerning.

I myself don't work on STA so I tested this on SPA. In SPA, I could not reproduce the issue. I first thought about non-initialized variables, so I deleted the `rlnClassNumber` column (from Class2D) before running the initial model job, but the result looked OK.

Which compiler did you use?

Can you make a tiny subset of your dataset that can reproduce this issue and share it with us?

**Comment by davidheisenberg** [comment] 2022-09-22 01:01
Hi there,

Thanks for the quick response. I am testing small subsets right now to see if I can recapitulate the problem and share with you the data.

I tested the job with the same result on two different machines actually. The one I mentioned above uses GCC 9.4.0. I also tried a Ubuntu 16.04 machine with 2080Tis where relion was compiled with GCC 5.4.0 and I found the same problem. Does that answer your question about which compiler? Sorry, I am not an expert computer person.

Thanks!

**Comment by biochem-fan** [comment] 2022-09-22 01:18
Yes, your compiler information is useful and enough. It is interesting that the problem occurred with GCC, which is what we use for development.

**Comment by davidheisenberg** [comment] 2022-09-22 01:33
What way would be best for me to send you some data? I found that I can reproduce the problem with ~7,000 subtomos (box size 56), and I am testing if it is reproducible with even less.

**Comment by biochem-fan** [comment] 2022-09-22 01:45
Could you please make it as small as possible, upload it to your Google Drive or DropBox and email the link to Takanori with CC to Sjors?

**Comment by biochem-fan** [comment] 2022-09-27 21:23
Fixed by @scheres. https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A2=ind2209&L=CCPEM&O=D&P=85612

**Closed by biochem-fan** 2022-09-27 21:23 UTC
