### ISSUE TITLE
Class 3D stalls on multiple GPU nodes

### ISSUE THREAD

**Issue by andreymalg** [3dem/relion#365] opened 2018-06-06 15:21 UTC
Hello,

When running C3D across multiple GPU nodes on our new cluster, the job always stalls after Maximization step for the 1st iteration. The output for iteration 1 is created successfully and there are no error messages that show up. If I cancel the job and continue from iteration 1 it will run to the end on a single node, but will once again stall after iteration 3. I do not see this problem when only requesting a single node. I am using OpenMPI 2.1.2, SLURM queuing, and latest version of relion. I have tried a variety of pool sizes, --dont_combine_weights, parallel IO Yes and No, but so far no luck.

Thank you

**Comment by bforsbe** [comment] 2018-06-06 15:29
There's lots of more info that would help diagnose the cause. The more the better, but in your case at least 

Compilation configuration (CUDA-version / GCC-version / OS / ... ) 
GPU model and RAM on the nodes. 
Command-line that you ran and the data-set size.
An explanation of what "the job always stalls" means. Do you see CPUs being used? The GPUs? Is it completely reproducible, and does it happen with all types of data? 

/Björn

**Comment by andreymalg** [comment] 2018-06-06 16:57
Hi Björn,

These are CentOS 7 nodes, 14-core Intel Broadwell, 256GB RAM, 4xTesla P100s, Nvidia driver 390.30, and SLURM queuing. Jobs were submitted with Cuda 8.0 and GCC 4.8.5. Data set is the relion_benchmark data from the wiki. Completely reproducible with this dataset. When the job stalls GPUs are not being used, CPUs are still being used and relion_refine_mpi shows up as a running task.  At the stalled iterations, Expectation and Maximization step are completed, the output for the iteration is created, but it does not continue to the next iteration.
Example of a submission script:

#SBATCH --partition=gpu
#SBATCH --gres=gpu:4
#SBATCH --ntasks=9
#SBATCH --cpus-per-task=5
#SBATCH --error=Class3D/job041/run.err
#SBATCH --output=Class3D/job041/run.out
#SBATCH --nodes=2
#SBATCH --exclusive
#SBATCH -t 12:00:00


# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE
module load cuda/8.0  fftw/3.3.7 openmpi/2.1.2 relion/2.1.0

#RUN
time mpirun -n 9 `which relion_refine_mpi` --continue Class3D/job041/run_it001_optimiser.star --o Class3D/job041/run_ct1 --dont_combine_weights_via_disc --no_parallel_disc_io --pool 10 --iter 25 --tau2_fudge 4 --particle_diameter 360 --oversampling 1 --healpix_order 2 --offset_range 5 --offset_step 2 --j 5 --gpu "" --random_seed 0

Thank you,

Andrey

**Comment by andreymalg** [comment] 2018-06-06 17:14
Looks like it has something to do with the particle size. Tried very similar submission with 2.5 as many particles, but box size of 256 instead of 360 and that job is running smoothly across multiple nodes.

**Comment by bforsbe** [comment] 2018-06-07 08:54
Interesting.  A smaller box working better indicates that it's a reconstruction issue, not a GPU-issue, at least. Otherwise it sounds like a network/memory-issue. When you say 2.5 times as many particles, did you add 150% new particles, or just duplicate lines in the particles.star-file?

**Comment by andreymalg** [comment] 2018-06-07 15:10
Hi Bjorn,

This was a separate data set I had on the cluster which I've taken past C2D. It has little over 250K particles of aldolase, compared to the ~100K particles of ribosomes in the benchmarking data.

**Comment by biochem-fan** [comment] 2019-06-26 21:05
Hopefully fixed in the latest commit.

**Closed by biochem-fan** 2019-06-26 21:05 UTC
