### ISSUE TITLE
I can`t download weight files when doing cmake .. 

### ISSUE THREAD

**Issue by unaginekomoyashi** [3dem/relion#1011] opened 2023-10-31 12:33 UTC
**Download problem when do cmake .. in build in relion5 installing **

When I cmake the relion5 installation specifying the python path in conda, I get the following error and cannot download the blush or pytorch weights. I think it is probably due to a problem with the proxy settings or my network limitations to the ftp site. I get the same error when I set proxy as an environment variable in the shell. If you know how to work around this, I would greatly appreciate it. Thank you in advance.

**Comment by unaginekomoyashi** [comment] 2023-10-31 12:39
File "/usr/local/bin/miniconda/envs/relion-5.0/lib/python3.10/urllib/request.py", line 1582, in ftp_open
    raise URLError(exp) from exp
urllib.error.URLError: <urlopen error [Errno 113] No route to host>

**Comment by biochem-fan** [comment] 2023-10-31 12:52
Duplicate of https://github.com/3dem/relion/issues/1003.
Please see the workaround there.

**Closed by biochem-fan** 2023-10-31 12:52 UTC
