### ISSUE TITLE
if relion 4.0.1 can Compilation succeeds with CUDA 8.0 or CUDA 9.0

### ISSUE THREAD

**Issue by gaorongchao** [3dem/relion#1114] opened 2024-04-23 10:08 UTC
This is a template for reporting bugs. Please fill in as much information as you can.

**Describe your problem**
install relion 4.0.1 failed.
**Environment:**
 - OS: [e.g. CentOS Linux release 7.4.1708 (Core)]
 - gcc/7.2.0
 - GPU: Tesla P100
 - memery 503G

   ```
[ 80%] Building CXX object src/apps/CMakeFiles/relion_gui_lib.dir/__/gui_jobwindow.cpp.o
Linking CXX executable ../../bin/relion_tomo_dark_erase
Linking CXX executable ../../bin/relion_autopick
Linking CXX executable ../../bin/relion_tomo_add_spheres
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `HandleError(cudaError, char const*, int)':
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0x9f): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `LaunchHandleError(cudaError, char const*, int)':
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0x1c7): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `bool MetaDataTable::setValue<int>(EMDLabel, int const&, long) [clone .constprop.189]':
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0x352): undefined reference to `MetaDataTable::addLabel(EMDLabel, std::string)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `bool MetaDataTable::setValue<double>(EMDLabel, double const&, long) [clone .constprop.190]':
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0x41f): undefined reference to `MetaDataTable::addLabel(EMDLabel, std::string)'
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0x4a5): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `LaunchHandleError(cudaError, char const*, int) [clone .constprop.194]':
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0x5dd): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `HandleError(cudaError, char const*, int) [clone .constprop.195]':
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0x6f5): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `void runCenterFFT<float>(AccPtr<float>&, int, int, bool, int) [clone .constprop.184]':
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0x899): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `AutoPickerCuda::calculateStddevAndMeanUnderMask(AccPtr<float2>&, AccPtr<float2>&, AccPtr<float2>&, int, AccPtr<float>&, AccPtr<float>&, unsigned long, unsigned long, unsigned long, unsigned long)':
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0x150a): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o):tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0x15d1): more undefined references to `RelionError::RelionError(std::string const&, std::string const&, long)' follow
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `MultidimArray<double>::resize(long, long, long, long) [clone .constprop.185]':
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0x2911): undefined reference to `FileName::addExtension(std::string const&) const'
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0x2a3a): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0x2d6c): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0x2e4d): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0x301c): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `AutoPickerCuda::autoPickOneMicrograph(FileName&, long)':
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0x3bd5): undefined reference to `MetaDataContainer::getValue(long, std::string&) const'
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0x67fb): undefined reference to `FileName::compose(std::string const&, long, std::string const&, int)'
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0x69d7): undefined reference to `FileName::compose(std::string const&, long, std::string const&, int)'
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0x6d77): undefined reference to `FileName::compose(std::string const&, long, std::string const&, int)'
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0x6f36): undefined reference to `FileName::compose(std::string const&, long, std::string const&, int)'
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0x9a6f): undefined reference to `MetaDataTable::addLabel(EMDLabel, std::string)'
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0xa145): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0xac24): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `AutoPickerCuda::run()':
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text+0xb00e): undefined reference to `FileName::beforeLastOf(std::string const&) const'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `CudaCustomAllocator::alloc(unsigned long)':
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text._ZN19CudaCustomAllocator5allocEm[_ZN19CudaCustomAllocator5allocEm]+0x2f9): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `CudaFFT::forward()':
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text._ZN7CudaFFT7forwardEv[_ZN7CudaFFT7forwardEv]+0x9e): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `CudaFFT::backward()':
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text._ZN7CudaFFT8backwardEv[_ZN7CudaFFT8backwardEv]+0x9e): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `AccPtr<float>::hostAlloc()':
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text._ZN6AccPtrIfE9hostAllocEv[_ZN6AccPtrIfE9hostAllocEv]+0x7b): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `AccPtr<float>::AccPtr(unsigned long, CudaCustomAllocator*)':
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text._ZN6AccPtrIfEC2EmP19CudaCustomAllocator[_ZN6AccPtrIfEC5EmP19CudaCustomAllocator]+0xa2): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o):tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text._ZN6AccPtrI6float2EC2EmP19CudaCustomAllocator[_ZN6AccPtrI6float2EC5EmP19CudaCustomAllocator]+0xa2): more undefined references to `RelionError::RelionError(std::string const&, std::string const&, long)' follow
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `MultidimArray<double>::resizeNoCp(long, long, long, long)':
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text._ZN13MultidimArrayIdE10resizeNoCpEllll[_ZN13MultidimArrayIdE10resizeNoCpEllll]+0x180): undefined reference to `FileName::addExtension(std::string const&) const'
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text._ZN13MultidimArrayIdE10resizeNoCpEllll[_ZN13MultidimArrayIdE10resizeNoCpEllll]+0x29a): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text._ZN13MultidimArrayIdE10resizeNoCpEllll[_ZN13MultidimArrayIdE10resizeNoCpEllll]+0x430): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text._ZN13MultidimArrayIdE10resizeNoCpEllll[_ZN13MultidimArrayIdE10resizeNoCpEllll]+0x50e): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text._ZN13MultidimArrayIdE10resizeNoCpEllll[_ZN13MultidimArrayIdE10resizeNoCpEllll]+0x5b0): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `Image<int>::writeIMAGIC(long, int, DataType)':
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE11writeIMAGICEli8DataType[_ZN5ImageIiE11writeIMAGICEli8DataType]+0x50): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `Image<int>::_write(FileName const&, fImageHandler&, long, bool, WriteMode, DataType)':
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlb9WriteMode8DataType[_ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlb9WriteMode8DataType]+0x86): undefined reference to `FileName::decompose(long&, std::string&) const'
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlb9WriteMode8DataType[_ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlb9WriteMode8DataType]+0x574): undefined reference to `FileName::contains(std::string const&) const'
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlb9WriteMode8DataType[_ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlb9WriteMode8DataType]+0x5cb): undefined reference to `FileName::contains(std::string const&) const'
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlb9WriteMode8DataType[_ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlb9WriteMode8DataType]+0x7fd): undefined reference to `FileName::contains(std::string const&) const'
tmpxft_00007f13_00000000-4_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlb9WriteMode8DataType[_ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlb9WriteMode8DataType]+0x96e): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'

tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZNSt6vectorI13MultidimArrayIdESaIS1_EE17_M_default_appendEm[_ZNSt6vectorI13MultidimArrayIdESaIS1_EE17_M_default_appendEm]+0xb51): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZNSt6vectorI13MultidimArrayIdESaIS1_EE17_M_default_appendEm[_ZNSt6vectorI13MultidimArrayIdESaIS1_EE17_M_default_appendEm]+0xcdd): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `void AccUtilities::normalizeAndTransformImage<MlOptimiserCuda>(AccPtr<float>&, MultidimArray<tComplex<double> >&, MlOptimiserCuda*, unsigned long, unsigned long, unsigned long)':
tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN12AccUtilities26normalizeAndTransformImageI15MlOptimiserCudaEEvR6AccPtrIfER13MultidimArrayI8tComplexIdEEPT_mmm[_ZN12AccUtilities26normalizeAndTransformImageI15MlOptimiserCudaEEvR6AccPtrIfER13MultidimArrayI8tComplexIdEEPT_mmm]+0xb2b): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o):tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN12AccUtilities26normalizeAndTransformImageI15MlOptimiserCudaEEvR6AccPtrIfER13MultidimArrayI8tComplexIdEEPT_mmm[_ZN12AccUtilities26normalizeAndTransformImageI15MlOptimiserCudaEEvR6AccPtrIfER13MultidimArrayI8tComplexIdEEPT_mmm]+0xbd1): more undefined references to `RelionError::RelionError(std::string const&, std::string const&, long)' follow
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `MultidimArray<bool>::coreAllocate()':
tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE12coreAllocateEv[_ZN13MultidimArrayIbE12coreAllocateEv]+0x65): undefined reference to `FileName::addExtension(std::string const&) const'
tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE12coreAllocateEv[_ZN13MultidimArrayIbE12coreAllocateEv]+0x154): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE12coreAllocateEv[_ZN13MultidimArrayIbE12coreAllocateEv]+0x1d0): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE12coreAllocateEv[_ZN13MultidimArrayIbE12coreAllocateEv]+0x252): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE12coreAllocateEv[_ZN13MultidimArrayIbE12coreAllocateEv]+0x2b3): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE12coreAllocateEv[_ZN13MultidimArrayIbE12coreAllocateEv]+0x2f9): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o):tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE12coreAllocateEv[_ZN13MultidimArrayIbE12coreAllocateEv]+0x34c): more undefined references to `RelionError::RelionError(std::string const&, std::string const&, long)' follow
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `MultidimArray<bool>::resizeNoCp(long, long, long, long)':
tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE10resizeNoCpEllll[_ZN13MultidimArrayIbE10resizeNoCpEllll]+0x180): undefined reference to `FileName::addExtension(std::string const&) const'
tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE10resizeNoCpEllll[_ZN13MultidimArrayIbE10resizeNoCpEllll]+0x296): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE10resizeNoCpEllll[_ZN13MultidimArrayIbE10resizeNoCpEllll]+0x410): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE10resizeNoCpEllll[_ZN13MultidimArrayIbE10resizeNoCpEllll]+0x4e6): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE10resizeNoCpEllll[_ZN13MultidimArrayIbE10resizeNoCpEllll]+0x588): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `arrayByArray(MultidimArray<tComplex<double> > const&, MultidimArray<tComplex<double> > const&, MultidimArray<tComplex<double> >&, char)':
tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._Z12arrayByArrayRK13MultidimArrayI8tComplexIdEES4_RS2_c[_Z12arrayByArrayRK13MultidimArrayI8tComplexIdEES4_RS2_c]+0xdd): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o):tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._Z30getAllSquaredDifferencesCoarseI15MlOptimiserCudaEvjR21OptimisationParamtersR18SamplingParametersP11MlOptimiserPT_R6AccPtrIfE13AccPtrFactoryi[_Z30getAllSquaredDifferencesCoarseI15MlOptimiserCudaEvjR21OptimisationParamtersR18SamplingParametersP11MlOptimiserPT_R6AccPtrIfE13AccPtrFactoryi]+0x26a9): more undefined references to `RelionError::RelionError(std::string const&, std::string const&, long)' follow
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `std::vector<MultidimArray<double>, std::allocator<MultidimArray<double> > >::_M_fill_insert(__gnu_cxx::__normal_iterator<MultidimArray<double>*, std::vector<MultidimArray<double>, std::allocator<MultidimArray<double> > > >, unsigned long, MultidimArray<double> const&)':
tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZNSt6vectorI13MultidimArrayIdESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_[_ZNSt6vectorI13MultidimArrayIdESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_]+0x503): undefined reference to `FileName::addExtension(std::string const&) const'
tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZNSt6vectorI13MultidimArrayIdESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_[_ZNSt6vectorI13MultidimArrayIdESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_]+0x62d): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZNSt6vectorI13MultidimArrayIdESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_[_ZNSt6vectorI13MultidimArrayIdESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_]+0xe19): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZNSt6vectorI13MultidimArrayIdESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_[_ZNSt6vectorI13MultidimArrayIdESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_]+0xfdb): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZNSt6vectorI13MultidimArrayIdESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_[_ZNSt6vectorI13MultidimArrayIdESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_]+0x1077): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `void storeWeightedSums<MlOptimiserCuda>(OptimisationParamters&, SamplingParameters&, MlOptimiser*, MlOptimiserCuda*, std::vector<IndexedDataArray, std::allocator<IndexedDataArray> >&, std::vector<ProjectionParams, std::allocator<ProjectionParams> >&, std::vector<std::vector<IndexedDataArrayMask, std::allocator<IndexedDataArrayMask> >, std::allocator<std::vector<IndexedDataArrayMask, std::allocator<IndexedDataArrayMask> > > >&, AccPtrFactory, int, std::vector<AccPtrBundle, std::allocator<AccPtrBundle> >&)':
tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._Z17storeWeightedSumsI15MlOptimiserCudaEvR21OptimisationParamtersR18SamplingParametersP11MlOptimiserPT_RSt6vectorI16IndexedDataArraySaISA_EERS9_I16ProjectionParamsSaISE_EERS9_IS9_I20IndexedDataArrayMaskSaISI_EESaISK_EE13AccPtrFactoryiRS9_I12AccPtrBundleSaISP_EE[_Z17storeWeightedSumsI15MlOptimiserCudaEvR21OptimisationParamtersR18SamplingParametersP11MlOptimiserPT_RSt6vectorI16IndexedDataArraySaISA_EERS9_I16ProjectionParamsSaISE_EERS9_IS9_I20IndexedDataArrayMaskSaISI_EESaISK_EE13AccPtrFactoryiRS9_I12AccPtrBundleSaISP_EE]+0x2f00): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o):tmpxft_00007f02_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._Z17storeWeightedSumsI15MlOptimiserCudaEvR21OptimisationParamtersR18SamplingParametersP11MlOptimiserPT_RSt6vectorI16IndexedDataArraySaISA_EERS9_I16ProjectionParamsSaISE_EERS9_IS9_I20IndexedDataArrayMaskSaISI_EESaISK_EE13AccPtrFactoryiRS9_I12AccPtrBundleSaISP_EE[_Z17storeWeightedSumsI15MlOptimiserCudaEvR21OptimisationParamtersR18SamplingParametersP11MlOptimiserPT_RSt6vectorI16IndexedDataArraySaISA_EERS9_I16ProjectionParamsSaISE_EERS9_IS9_I20IndexedDataArrayMaskSaISI_EESaISK_EE13AccPtrFactoryiRS9_I12AccPtrBundleSaISP_EE]+0x56a4): more undefined references to `RelionError::RelionError(std::string const&, std::string const&, long)' follow
collect2: error: ld returned 1 exit status
make[2]: *** [bin/relion_autopick] Error 1
make[1]: *** [src/apps/CMakeFiles/autopick.dir/all] Error 2
[ 81%] Building CXX object src/apps/CMakeFiles/relion_gui_lib.dir/__/Healpix_2.15a/healpix_base.cc.o
Linking CXX executable ../../bin/relion_ctf_refine_mpi
Linking CXX executable ../../bin/relion_tomo_discover_motif
Linking CXX executable ../../bin/relion_delete_blobs_2d
Linking CXX executable ../../bin/relion_tomo_delete_blobs
[ 81%] [ 81%] Built target discover_motif
Built target ctf_refine_mpi
[ 81%] Built target delete_blobs
[ 81%] Built target delete_blobs_2d
Linking CXX executable ../../bin/relion_class_ranker
[ 81%] Built target class_ranker
Linking CXX executable ../../bin/relion_ctf_mask_test
[ 81%] Built target ctf_mask_test
Linking CXX executable ../../bin/relion_align_symmetry
Linking CXX executable ../../bin/relion_tomo_catalogue_tomos
[ 81%] Built target align_symmetry
[ 81%] Built target catalogue_tomos
Linking CXX executable ../../bin/relion_tomo_bin_stack
[ 81%] Built target bin_stack
Linking CXX executable ../../bin/relion_estimate_gain
Linking CXX executable ../../bin/relion_ctf_toolbox
Linking CXX executable ../../bin/relion_demodulate
[ 81%] Built target estimate_gain
[ 81%] Built target ctf_toolbox
[ 81%] Built target demodulate
Linking CXX executable ../../bin/relion_tomo_Wiener_divide
[ 81%] Built target Wiener_divide
Linking CXX static library ../../lib/librelion_gui_lib.a
[ 81%] Built target relion_gui_lib
make: *** [all] Error 2

```

**Comment by biochem-fan** [comment] 2024-04-23 10:54
Please make sure `nvcc` and `mpicc` internally call the same version of GCC as picked up by `cmake`.

**Comment by gaorongchao** [comment] 2024-04-26 06:28
Thank you for you reply, This problem were solved!

**Comment by biochem-fan** [comment] 2024-04-26 07:32
What was the cause? Posting your fix before closing this issue would help others having the same problem.

**Comment by gaorongchao** [comment] 2024-04-28 01:18
just as your advice, I found there are have cuda 8, cuda 9, and gcc with 4.8.5 and 7.2.0, final I install sucess with cuda 8 and gcc 4.8.5. Thank you again.

**Closed** 2024-04-28 01:19 UTC
