### ISSUE TITLE
Build_type=Benchmarking fails

### ISSUE THREAD

**Issue by bollig** [3dem/relion#725] opened 2021-01-19 22:05 UTC
Building with `build_type=Benchmarking` enables the TIMING macro, which results in double definition of timer in renderEER.cpp and motioncorr_runner.cpp. 

 ```
    715    [ 66%] Linking CXX executable ../../bin/relion_postprocess_mpi
     716    cd /tmp/ec2-user/spack-stage/spack-stage-relion-3.1.1-v6743um4etzleyhkahtc2zxzeskdbv6m/spack-build-v6743um/src/apps && /shared/spack-0.15/opt
            /spack/linux-amzn2-skylake_avx512/gcc-7.3.1/cmake-3.19.2-glhmhw6lsvorl5lkskw5dhpq7kgsmflk/bin/cmake -E cmake_link_script CMakeFiles/postproce
            ss_mpi.dir/link.txt --verbose=1
     717    /opt/amazon/openmpi/bin/mpicxx -g -fopenmp -std=c++0x -O3 -DNDEBUG   -DCUDA_BENCHMARK -DTIMING  -lmkl_intel_ilp64 -lmkl_core -lmkl_sequential
               -rdynamic CMakeFiles/postprocess_mpi.dir/postprocess_mpi.cpp.o -o ../../bin/relion_postprocess_mpi   -L/shared/spack-0.15/opt/spack/linux-
            amzn2-skylake_avx512/gcc-7.3.1/intel-tbb-2020.3-hvah3t5233bxruwivtbyuo5lh5awadbj/lib  -Wl,-rpath,/opt/amazon/openmpi/lib64:/shared/spack-0.15
            /opt/spack/linux-amzn2-skylake_avx512/gcc-7.3.1/intel-tbb-2020.3-hvah3t5233bxruwivtbyuo5lh5awadbj/lib:/shared/spack-0.15/opt/spack/linux-amzn
            2-skylake_avx512/gcc-7.3.1/libtiff-4.1.0-anvw4vtwatjo7e3tmi27rlnv5juhyk7f/lib::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
            :::::::::::::::::::::::::::::::::::::::::::::::::::: ../../lib/librelion_lib.a /opt/amazon/openmpi/lib64/libmpi.so -ldl -ltbb /shared/spack-0
            .15/opt/spack/linux-amzn2-skylake_avx512/gcc-7.3.1/libtiff-4.1.0-anvw4vtwatjo7e3tmi27rlnv5juhyk7f/lib/libtiff.so -lpng
     718    ../../lib/librelion_lib.a(renderEER.cpp.o):/tmp/ec2-user/spack-stage/spack-stage-relion-3.1.1-v6743um4etzleyhkahtc2zxzeskdbv6m/spack-src/src/
            renderEER.cpp:20: multiple definition of `timer'
     719    ../../lib/librelion_lib.a(motioncorr_runner.cpp.o):/tmp/ec2-user/spack-stage/spack-stage-relion-3.1.1-v6743um4etzleyhkahtc2zxzeskdbv6m/spack-
            src/src/motioncorr_runner.cpp:38: first defined here
  >> 720    collect2: error: ld returned 1 exit status
  >> 721    make[2]: *** [bin/relion_run_motioncorr_mpi] Error 1
```

**Comment by biochem-fan** [comment] 2021-01-19 22:10
Duplicate of #677.

This should be fixed in the `ver3.1` branch. If not, please reopen #677.

**Closed by biochem-fan** 2021-01-19 22:10 UTC
