### ISSUE TITLE
GPU Mem Use clarification

### ISSUE THREAD

**Issue by craigyk** [3dem/relion#654] opened 2020-08-09 19:39 UTC
This is probably not a bug, but my last recollection was that it should be possible to use a box size of ~1000x1000 in 11GB of GPU mem with a padding of 1.  Is this no longer the case (or was it ever?).  I added some printf statements once I saw CUDAMemAlloc errors, and noticed with a box size of 1024, Relion was trying to allocated 16GB of GPU RAM.  I would have guessed each map FFT in float would have been ~8GB, but it seems to be trying to grab twice that.  Is that for each half map?  I thought the independent halfsets were split between different MPI processes?

Thanks for clarifications!

**Comment by biochem-fan** [comment] 2020-08-09 19:47
1000 px should be OK with `--pad 1`. Are you sure you built with GPU single precision (the default)?

Are you using version 3.1.0 (1e738ec) or something newer in the ver3.1 branch?

**Comment by craigyk** [comment] 2020-08-09 19:53
Yes, I'm using the latest commits to the v3.1 branch

**Comment by craigyk** [comment] 2020-08-09 20:02
I am reverting to 3.1.0 tag and trying that...

**Comment by bforsbe** [comment] 2020-08-09 21:08
There's a weight array for the weighted back-projection, so you have to bump the estimate by 50%, putting you at 12GB, unless you accounted for that.

**Comment by craigyk** [comment] 2020-08-10 04:36
> There's a weight array for the weighted back-projection, so you have to bump the estimate by 50%, putting you at 12GB, unless you accounted for that.

I didn't account for that, but I also forgot that the FFT of a real-valued volume would not need 2X the memory.  In any case, it seems to be running great again with 11GB after reverting to 3.1.0

**Comment by biochem-fan** [comment] 2020-08-10 05:23
@arom4github Can you investigate this issue? Probably your new Projector/Backprojector initialization code is the cause. I would revert your commit if this cannot be fixed.

**Comment by arom4github** [comment] 2020-08-10 05:30
Hi,

it's easy to fix. 
In a day or so I will push the next PR. It will bring FFT stuff for the projection (Expectation setup) on GPU and fix this issue.
I already have a code which checks available GPU memory and in case there is not enough mem on the GPU, it performs calculations on CPU side.
 
I didn't have a dataset to test such big images. Where can I get it?

Alexey

**Comment by biochem-fan** [comment] 2020-08-10 05:42
Thanks.

> I didn't have a dataset to test such big images. Where can I get it?

1. Make the reference large:
  ```relion_image_handler --i ref.mrc --o ref_1K.mrc --new_box 1000```
2. Use it in`relion_refine-mpi` with `--ref ref_1K.mrc --pad 1 --trust_ref_size`.

This should force RELION to project the small particles into a large box. If this does not work, we have to make input particles large too (I will check the command later today).

**Comment by biochem-fan** [comment] 2020-08-14 10:51
@craigyk Can you test @arom4github's `optim4` branch at https://github.com/arom4github/relion/tree/optim4?

**Comment by craigyk** [comment] 2020-08-16 04:23
@biochem-fan, just saw this, will do so when I get the chance

**Comment by biochem-fan** [comment] 2020-08-16 10:07
@craigyk Thanks. After your confirmation, I will merge this to be released as 3.1.1 in September (together with EER support).

**Comment by craigyk** [comment] 2020-08-16 19:44
@biochem-fan , OK I've confirmed that the optim4 branch does not crash.  I see the GPU to CPU setup warnings, hard to tell if there is a performance regression or just variability between these builds.  I reran twice to make sure things were cached for both builds,  my expectation timings for iterations 1, 2 and 3, note the weird swap in timing between iterations 2 and 3:

3.1.0 build
iter 1 2.33 min
iter 2 7.07 min
iter 3 2.22 min

optim4
iter 1 2.27 min
iter 2 2.35 min
iter 3 6.43 min

**Comment by biochem-fan** [comment] 2020-08-16 20:06
@craigyk Thank you very much for testing. Are you running 1 MPI process per GPU?

The warning can be ignored (probably I will remove it). When the warning is displayed, it is using the old (CPU) code path.

**Comment by biochem-fan** [comment] 2020-08-16 20:26
Merged to `devel-nvidia-optim4` branch for local testing.

**Comment by craigyk** [comment] 2020-08-24 20:33
yes, it was 1 process per GPU, 4 threads per process.

**Closed** 2020-09-26 19:56 UTC
