### ISSUE TITLE
2D Classification error with 2.1

### ISSUE THREAD

**Issue by gtolun** [3dem/relion#256] opened 2017-07-11 21:09 UTC
Hi,
After MotionCor2 gain correction and alignment, followed by Gctf, I manually picked about 1800 particles to be used for Auto-picking in RELION.

When I ran a 2D classification with these extracted particles, I got the following error:

`  2: MPI_ERR_TYPE: invalid datatype
  2: MPI_ERR_TYPE: invalid datatype
  1: MPI_ERR_TYPE: invalid datatype
  1: MPI_ERR_TYPE: invalid datatype
terminate called after throwing an instance of 'RelionError'
terminate called after throwing an instance of 'RelionError'
[hawk:28428] *** Process received signal ***
[hawk:28429] *** Process received signal ***
[hawk:28429] Signal: Aborted (6)
[hawk:28429] Signal code:  (-6)
[hawk:28428] Signal: Aborted (6)
[hawk:28428] Signal code:  (-6)
[hawk:28429] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x10330)[0x7fbc417ef330]
[hawk:28429] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x7fbc4144cc37]
[hawk:28429] [ 2] [hawk:28428] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x10330)[0x7f0bc9b6d330]
[hawk:28428] [ 1] /lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7fbc41450028]
[hawk:28429] [ 3] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x155)[0x7fbc41c73535]
[hawk:28429] [ 4] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x7f0bc97cac37]
[hawk:28428] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7f0bc97ce028]
[hawk:28428] [ 3] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5e6d6)[0x7fbc41c716d6]
[hawk:28429] [ 5] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x155)[0x7f0bc9ff1535]
[hawk:28428] [ 4] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5e703)[0x7fbc41c71703]
[hawk:28429] [ 6] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5e922)[0x7fbc41c71922]
[hawk:28429] [ 7] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5e6d6)[0x7f0bc9fef6d6]
[hawk:28428] [ 5] /home/username/relion21Beta/build/lib/librelion_lib.so(_ZN7MpiNode16report_MPI_ERROREi+0x136)[0x7fbc426db8e6]
[hawk:28429] *** End of error message ***
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5e703)[0x7f0bc9fef703]
[hawk:28428] [ 6] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5e922)[0x7f0bc9fef922]
[hawk:28428] [ 7] /home/username/relion21Beta/build/lib/librelion_lib.so(_ZN7MpiNode16report_MPI_ERROREi+0x136)[0x7f0bcaa598e6]
[hawk:28428] *** End of error message ***`

When I tried exactly the same thing from the same project folder, using RELION 2, it ran just fine.

This is on Linux Mint 17.3 Cinnamon, no GPU usage.

Thanks.

**Comment by bforsbe** [comment] 2017-07-13 10:19
Duplicate of #234

**Closed by bforsbe** 2017-07-13 10:19 UTC
