### ISSUE TITLE
Error with ctffind4.1+

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#186] opened 2017-01-13 21:17 UTC
Originally reported by: **Roxana (Bitbucket: [roxibelo_bit](https://bitbucket.org/roxibelo_bit), GitHub: Unknown)**

----------------------------------------

We get an error message while running relion2.0 ctf correction with ctffind4.1.5 or gctf
When we run the ctf correction using Ctffind4.0.17 everything works fine.

 The program crashes and shows the following error:

$ `which relion_run_ctffind_mpi` --i Import/job001/micrographs.star --o CtfFind/job003/ --CS 2 --HT 200 --AmpCnst 0.1 --XMAG 10000 --DStep 2.12 --Box 512 --ResMin 30 --ResMax 10 --dFMin 5000 --dFMax 50000 --FStep 500 --dAst 100 --ctffind_exe /programs/x86_64-linux/ctffind4/4.1.5/bin/ctffind --ctfWin -1 --is_ctffind4 .
 === RELION MPI setup ===
 + Number of MPI processes             = 1
 + Master  (0) runs on host            = XXXXXXXX
 =================
 Using CTFFIND executable in: /programs/x86_64-linux/ctffind4/4.1.5/bin/ctffind
 to estimate CTF parameters for the following micrographs:
  * Micrographs/c24399.mrc
  * Micrographs/c24401.mrc
  * Micrographs/c24402.mrc
  * Micrographs/c24403.mrc
  * Micrographs/c24405.mrc
  * Micrographs/c24406.mrc
  * Micrographs/c24408.mrc
  * Micrographs/c24409.mrc
  * Micrographs/c24410.mrc
  * Micrographs/c24411.mrc
  * Micrographs/c24414.mrc
  * Micrographs/c24415.mrc
  * Micrographs/c24418.mrc
  * Micrographs/c24419.mrc
  * Micrographs/c24420.mrc
  * Micrographs/c24421.mrc
  * Micrographs/c24422.mrc
  * Micrographs/c24423.mrc
  * Micrographs/c24424.mrc
  * Micrographs/c24425.mrc
  * Micrographs/c24427.mrc
  * Micrographs/c24435.mrc
  * Micrographs/c24436.mrc
  * Micrographs/c24437.mrc
  * Micrographs/c24440.mrc
  * Micrographs/c24441.mrc
  * Micrographs/c24445.mrc
  * Micrographs/c24447.mrc
  * Micrographs/c24449.mrc
  * Micrographs/c24450.mrc
  * Micrographs/c24453.mrc
  * Micrographs/c24455.mrc
  * Micrographs/c24456.mrc
  * Micrographs/c24461.mrc
  * Micrographs/c24462.mrc
  * Micrographs/c24464.mrc
  * Micrographs/c24465.mrc
  * Micrographs/c24467.mrc
  * Micrographs/c24468.mrc
  * Micrographs/c24471.mrc
  * Micrographs/c24473.mrc
  * Micrographs/c24474.mrc
  * Micrographs/c24475.mrc
  * Micrographs/c24476.mrc
  * Micrographs/c24477.mrc
  * Micrographs/c24479.mrc
  * Micrographs/c24481.mrc
  * Micrographs/c24482.mrc
  * Micrographs/c24483.mrc
  * Micrographs/c24484.mrc
  * Micrographs/c24486.mrc
  * Micrographs/c24487.mrc
  * Micrographs/c24488.mrc
  * Micrographs/c24489.mrc
  * Micrographs/c24490.mrc
  * Micrographs/c24492.mrc
  * Micrographs/c24493.mrc
  * Micrographs/c24494.mrc
  * Micrographs/c24496.mrc
  * Micrographs/c24497.mrc
  * Micrographs/c24498.mrc
  * Micrographs/c24500.mrc
  * Micrographs/c24502.mrc
 Estimating CTF parameters using Niko Grigorieff's CTFFIND ...
000/??? sec ~~(,_,">                                                          [oo]WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24399_ctffind4.com
WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24401_ctffind4.com
0.02/1.05 min ~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24402_ctffind4.com
   1/  31 sec .~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24403_ctffind4.com
   2/  42 sec ..~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24405_ctffind4.com
   2/  31 sec ...~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24406_ctffind4.com
   2/  25 sec ....~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24408_ctffind4.com
   2/  21 sec .....~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24409_ctffind4.com
   2/  18 sec ......~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24410_ctffind4.com
   2/  15 sec .......~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24411_ctffind4.com
   3/  21 sec ........~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24414_ctffind4.com
   3/  18 sec .........~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24415_ctffind4.com
   3/  17 sec ..........~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24418_ctffind4.com
   3/  15 sec ...........~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24419_ctffind4.com
   3/  14 sec ............~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24420_ctffind4.com
   3/  13 sec .............~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24421_ctffind4.com
   4/  16 sec ..............~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24422_ctffind4.com
   4/  15 sec ...............~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24423_ctffind4.com
   4/  14 sec ................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24424_ctffind4.com
   4/  14 sec .................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24425_ctffind4.com
   4/  13 sec ..................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24427_ctffind4.com
   4/  12 sec ...................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24435_ctffind4.com
   5/  15 sec ...................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24436_ctffind4.com
   5/  14 sec ....................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24437_ctffind4.com
   5/  13 sec .....................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24440_ctffind4.com
   5/  13 sec ......................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24441_ctffind4.com
   5/  12 sec .......................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24445_ctffind4.com
   5/  12 sec ........................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24447_ctffind4.com
   6/  14 sec .........................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24449_ctffind4.com
   6/  13 sec ..........................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24450_ctffind4.com
   6/  13 sec ...........................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24453_ctffind4.com
   6/  12 sec ............................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24455_ctffind4.com
   6/  12 sec .............................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24456_ctffind4.com
   6/  11 sec ..............................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24461_ctffind4.com
   7/  13 sec ...............................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24462_ctffind4.com
   7/  12 sec ................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24464_ctffind4.com
   7/  12 sec .................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24465_ctffind4.com
   7/  12 sec ..................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24467_ctffind4.com
   7/  11 sec ...................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24468_ctffind4.com
   7/  11 sec ....................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24471_ctffind4.com
   8/  12 sec .....................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24473_ctffind4.com
   8/  12 sec ......................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24474_ctffind4.com
   8/  12 sec .......................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24475_ctffind4.com
   8/  12 sec .......................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24476_ctffind4.com
   8/  11 sec ........................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24477_ctffind4.com
   8/  11 sec .........................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24479_ctffind4.com
   9/  12 sec ..........................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24481_ctffind4.com
   9/  12 sec ...........................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24482_ctffind4.com
   9/  12 sec ............................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24483_ctffind4.com
   9/  11 sec .............................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24484_ctffind4.com
   9/  11 sec ..............................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24486_ctffind4.com
   9/  11 sec ...............................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24487_ctffind4.com
  10/  12 sec ................................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24488_ctffind4.com
  10/  12 sec .................................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24489_ctffind4.com
  10/  11 sec ..................................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24490_ctffind4.com
  10/  11 sec ...................................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24492_ctffind4.com
  10/  11 sec ....................................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24493_ctffind4.com
  10/  11 sec .....................................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24494_ctffind4.com
  11/  12 sec ......................................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24496_ctffind4.com
  11/  11 sec .......................................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24497_ctffind4.com
  11/  11 sec ........................................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24498_ctffind4.com
  11/  11 sec .........................................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24500_ctffind4.com
  11/  11 sec ..........................................................~~(,_,">WARNING: there was an error in executing: csh CtfFind/job003/Micrographs/c24502_ctffind4.com
  12/  12 sec ............................................................~~(,_,">
 WARNING: skipping, since cannot get CTF values for Micrographs/c24399.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24401.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24402.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24403.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24405.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24406.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24408.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24409.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24410.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24411.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24414.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24415.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24418.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24419.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24420.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24421.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24422.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24423.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24424.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24425.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24427.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24435.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24436.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24437.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24440.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24441.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24445.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24447.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24449.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24450.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24453.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24455.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24456.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24461.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24462.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24464.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24465.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24467.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24468.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24471.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24473.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24474.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24475.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24476.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24477.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24479.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24481.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24482.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24483.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24484.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24486.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24487.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24488.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24489.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24490.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24492.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24493.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24494.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24496.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24497.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24498.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24500.mrc
 WARNING: skipping, since cannot get CTF values for Micrographs/c24502.mrc
 Done! Written out: CtfFind/job003/micrographs_ctf.star

Any suggestions?
Thank you
Roxana

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/186

**Comment by baibing7713661** [comment] 2017-11-09 19:59
I have the same problem. Do we already have solution for this? I have tried different version of Ctffind4.1 and results are the same.

WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for 
 WARNING: skipping, since cannot get CTF values for

**Comment by Fravadona** [comment] 2017-12-04 10:53
I have the same error than baibing7713661, doing the tutorial with RELION 2.1-beta-1.
The problem is an empty file list passed to ctffind. I determined that the bug is in ctffind_runner.cpp. I'll try to make a patch.

**Comment by duanjingqi** [comment] 2017-12-11 21:21
You probably have to install tcsh or csh package to enable ctffind.

**Comment by Fravadona** [comment] 2017-12-11 22:17
My patch is wrong. The problem comes from the "do without dose weight" option in the CTF configuration, which is only correct after doing the motion correction with MotionCor2 (not with unblur&summovie).

**Comment by martinpev** [comment] 2018-01-03 18:26
Hi all. I was trying to use CTFFIND4.1.8 with Relion-2.1.0 on an intel 64 ubuntu 16.04 LS computer (no GPUs) and doing the relion21 tutorial, but came across the "skipping, since cannot get CTF values" error in the relion GUI after initiating the CTF estimation job. I then attempted to run ctffind from the console but came across another problem "error while loading shared libraries: libtiff.so.3: cannot open shared object file: No such file or directory." 

''''Installing latest libtiff library"""
sudo apt install libtiff5

Found that everything was up to date.

"""Locate libtiff"""
locate -b libtiff

Determined that there was no libtiff.so.3 - only libtiff.so.5

"""Create symlink to redirect program to look for libtiff.so.5 [64-bit system]"""
sudo ln -s /usr/lib/x86_64-linux-gnu/libtiff.so.5 /usr/lib/x86_64-linux-gnu/libtiff.so.3

ctffind now works in the console AND completed the CTF estimation in the relion GUI

---> https://askubuntu.com/questions/44132/how-do-i-install-libtiff-so-3

**Comment by jdkruzr** [comment] 2018-02-21 22:49
@Fravadona I hope your answer gets upvoted some more. The tutorial is wrong. Your setting is the correct one in order to stop CTFFIND from getting a bunch of blank input files.

**Comment by biochem-fan** [comment] 2019-02-25 13:59
Not relevant for 3.0. Closing.

**Closed by biochem-fan** 2019-02-25 13:59 UTC
Labels: bug, major

**Comment by wgl91** [comment] 2020-04-02 17:49
I got the same error using 3.1. I found out that Relion was copying all the folders in the path to my data into the /.Node temporary storage. It was using symlinks to direct to the actual data. The symlinks were all broken, so I just created a new symlink in my /ctffind job to the folder with my data and that fixed the problem

**Comment by truatpasteurdotfr** [comment] 2020-09-08 15:14
Just a note for those who happen to work with the data on a CIFS shared space... 

$ relion_run_ctffind <...>
`WARNING: skipping, since cannot get CTF values` is happening on our CentOS-7 machines with a default cifs mount.
stracing yields:
```
59803 symlink("/cifs/zeus/sia_esmmc-tru/xxx//MotionCorr/job002/FoilHole_26584351_Data_26591927_26591929_20200826_183300_Fractions.mrc", "CtfFind/job003/FoilHole_26584351_Data_26591927_26591929_20200826_183300_Fractions.mrc") = -1 EOPNOTSUPP (Operation not supported)
```
The solution for us was to add the `mfsymlinks` options for cifs. Hoping that helps!
