### ISSUE TITLE
WARNING: norm_correction during 2D classification and Refine3D

### ISSUE THREAD

**Issue by N-Bogdanovic-85** [3dem/relion#848] opened 2022-02-03 18:15 UTC
This is a template for reporting bugs. Please fill in as much information as you can.

**Describe your problem**
I have switched from the Relion 3.1 to Relion 4.0 beta and the 2D classification works properly in a random fashion. This means that after 2 consecutive rounds of 2D classification and selection of good classes, the third round with selected particles displays the "WARNING: norm_correction......." (report added in the error-report-2D.txt file). In addition, in attempts to run the 3D refinement, with the currently selected particles and volumes produced from my earlier dataset (relion 3.1 and same data collection parameters, same microscope), the same error comes up (please see the attached file error-report-3D.txt). I am not sure why this happens, when 3D classification run normally and some 2D classifications run normally too. I also explored the flag --dont_check_norm and it seems that some jobs ignore it and some run normally. It all seems pretty random, but might be caused by some bad particles... I have not had this issue with Relion 3.1 in similar datasets.

**Environment:**
 - OS: [CentOs Linux 7]
 - MPI runtime: [OpenMPI 3.2.1]
 - RELION version [RELION-4.0-beta-2] 
 - Memory: [384 GB]
 - GPU: [8x RTX A6000]

**Dataset:**
 - Box size: [420 px]
 - Pixel size: [1.06 Å/px]
 - Number of particles: [650,000-1,000,000]
 - Description: [A tetrameric membrane protein of about 400 kDa in total]

**Job options:**
 - Type of job: [2D classification]
 - Number of MPI processes: [1]
 - Number of threads: [40]
 - Full command (see `note.txt` in the job directory):
   ```
   `which relion_refine` --o Class2D/job052/run --grad --class_inactivity_threshold 0.1 --grad_write_iter 10 --iter 200 --i Select/job051/particles.star --dont_combine_weights_via_disc --pool 300 --pad 2  --ctf  --tau2_fudge 2 --particle_diameter 360 --K 200 --flatten_solvent  --zero_mask  --center_classes  --oversampling 1 --psi_step 10 --offset_range 5 --offset_step 2 --allow_coarser_sampling --norm --scale  --j 40 --gpu "" --dont_check_norm --pipeline_control Class2D/job052/   ```

**Error message:**

Please cite the *full* error message as the example below.

```
gpu-ids not specified, threads will automatically be mapped to devices (incrementally).
 Thread 0 mapped to device 0
 Thread 1 mapped to device 0
 Thread 2 mapped to device 0
 Thread 3 mapped to device 0
 Thread 4 mapped to device 0
 Thread 5 mapped to device 1
 Thread 6 mapped to device 1
 Thread 7 mapped to device 1
 Thread 8 mapped to device 1
 Thread 9 mapped to device 1
 Thread 10 mapped to device 2
 Thread 11 mapped to device 2
 Thread 12 mapped to device 2
 Thread 13 mapped to device 2
 Thread 14 mapped to device 2
 Thread 15 mapped to device 3
 Thread 16 mapped to device 3
 Thread 17 mapped to device 3
 Thread 18 mapped to device 3
 Thread 19 mapped to device 3
 Thread 20 mapped to device 4
 Thread 21 mapped to device 4
 Thread 22 mapped to device 4
 Thread 23 mapped to device 4
 Thread 24 mapped to device 4
 Thread 25 mapped to device 5
 Thread 26 mapped to device 5
 Thread 27 mapped to device 5
 Thread 28 mapped to device 5
 Thread 29 mapped to device 5
 Thread 30 mapped to device 6
 Thread 31 mapped to device 6
 Thread 32 mapped to device 6
 Thread 33 mapped to device 6
 Thread 34 mapped to device 6
 Thread 35 mapped to device 7
 Thread 36 mapped to device 7
 Thread 37 mapped to device 7
 Thread 38 mapped to device 7
 Thread 39 mapped to device 7
 Running CPU instructions in double precision. 
 + WARNING: Changing psi sampling rate (before oversampling) to 5.625 degrees, for more efficient GPU calculations
 Initial subset size set to 3145
 Final subset size set to 31459
 Estimating initial noise spectra 
   5/   5 sec ............................................................~~(,_,">
 Estimating accuracies in the orientational assignment ... 
   0/   0 sec ............................................................~~(,_,">
 Auto-refine: Estimated accuracy angles= 999 degrees; offsets= 999 Angstroms
 CurrentResolution= 15.3517 Angstroms, which requires orientationSampling of at least 4.86486 degrees for a particle of diameter 360 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 268800
 OrientationalSampling= 5.625 NrOrientations= 64
 TranslationalSampling= 2.12 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 8601600
 OrientationalSampling= 2.8125 NrOrientations= 512
 TranslationalSampling= 1.06 NrTranslations= 84
=============================
 Gradient optimisation iteration 1 of 200 with 3145 particles (Step size 0.9)
  20/  20 sec ............................................................~~(,_,">
 Maximization ...
   4/   4 sec ............................................................~~(,_,">
 CurrentResolution= 2.13014 Angstroms, which requires orientationSampling of at least 0.677966 degrees for a particle of diameter 360 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 268800
 OrientationalSampling= 5.625 NrOrientations= 64
 TranslationalSampling= 2.12 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 8601600
 OrientationalSampling= 2.8125 NrOrientations= 512
 TranslationalSampling= 1.06 NrTranslations= 84
=============================
 Gradient optimisation iteration 2 of 200 with 3145 particles (Step size 0.9)
000/??? sec ~~(,_,">                                                          [oo] WARNING: norm_correction= 45.1706 for particle 173771 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 44.9355 for particle 574380 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 77.9689 for particle 435815 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 252.205 for particle 334057 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 1276.14 for particle 608816 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 168.65 for particle 463767 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 468.268 for particle 330646 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 18.4856 for particle 594875 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 50.2612 for particle 299546 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 40.0184 for particle 199141 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 634.339 for particle 339479 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 113.292 for particle 518258 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 28.0563 for particle 283207 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 477.792 for particle 187261 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 117191 for particle 595564 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 17.249 for particle 589562 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 77619.3 for particle 554290 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 1.38527e+08 for particle 466250 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 605.926 for particle 628068 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 20.294 for particle 105216 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 66.8745 for particle 497281 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 456.025 for particle 330584 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 280.163 for particle 241821 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 498.873 for particle 287184 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 3.33741e+06 for particle 162814 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 1543.08 for particle 573529 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 11063.6 for particle 606972 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 225.695 for particle 186229 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 14.3864 for particle 1954 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 47.3691 for particle 261921 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 12978 for particle 536626 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 21.8409 for particle 7640 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 22.5458 for particle 240790 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 258.827 for particle 463779 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 416.251 for particle 367998 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 9520.91 for particle 135598 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 21275.3 for particle 448976 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 7861.83 for particle 537133 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 72050 for particle 554321 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 1.82248e+07 for particle 521794 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 61.0232 for particle 439762 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 2.42483e+06 for particle 162796 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 81.3801 for particle 23635 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 10.8756 for particle 392398 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 274.819 for particle 279968 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 1169.7 for particle 11341 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 4586.11 for particle 440005 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 50.6037 for particle 497271 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 763.236 for particle 277421 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 1013.07 for particle 628417 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 561.393 for particle 426309 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 13.7566 for particle 621762 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 250.282 for particle 241896 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 3945.51 for particle 330666 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 173.186 for particle 241883 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 546.244 for particle 628100 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 19.8542 for particle 561115 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 2530.14 for particle 440019 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 14.6402 for particle 194728 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 30.9404 for particle 295013 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 142.67 for particle 516767 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 64968.5 for particle 428773 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 28.0802 for particle 49576 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 5194.81 for particle 287107 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 548.757 for particle 104372 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 476.728 for particle 484948 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 152.444 for particle 516745 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
2.67/2.67 min ............................................................~~(,_,">
 Maximization ...
  10/  10 sec ............................................................~~(,_,">
 CurrentResolution= 2.13014 Angstroms, which requires orientationSampling of at least 0.677966 degrees for a particle of diameter 360 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 268800
 OrientationalSampling= 5.625 NrOrientations= 64
 TranslationalSampling= 2.12 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 8601600
 OrientationalSampling= 2.8125 NrOrientations= 512
 TranslationalSampling= 1.06 NrTranslations= 84
=============================
 Gradient optimisation iteration 3 of 200 with 3145 particles (Step size 0.9)
000/??? sec ~~(,_,">                                                          [oo] WARNING: norm_correction= 10.0807 for particle 232496 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 34335.3 for particle 515736 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 8.22809e+06 for particle 337116 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 139174 for particle 373687 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 32.3743 for particle 449016 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 45.3286 for particle 130353 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 39.7971 for particle 162991 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 2860.33 for particle 366383 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 2624.2 for particle 386168 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 46.4233 for particle 393429 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 730.926 for particle 611217 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 10.5391 for particle 350172 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 15.2038 for particle 536618 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 19.2997 for particle 46275 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 487975 for particle 130195 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 5715.65 for particle 379510 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 186.781 for particle 595572 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 43.9613 for particle 453845 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 16.5516 for particle 287322 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 434747 for particle 130202 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 2761.97 for particle 546840 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 426.354 for particle 559584 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
2.37/2.37 min ............................................................~~(,_,">
 Maximization ...
   3/   3 sec ............................................................~~(,_,">
 CurrentResolution= 2.13014 Angstroms, which requires orientationSampling of at least 0.677966 degrees for a particle of diameter 360 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 268800
 OrientationalSampling= 5.625 NrOrientations= 64
 TranslationalSampling= 2.12 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 8601600
 OrientationalSampling= 2.8125 NrOrientations= 512
 TranslationalSampling= 1.06 NrTranslations= 84
=============================
 Gradient optimisation iteration 4 of 200 with 3145 particles (Step size 0.9)
000/??? sec ~~(,_,">                                                          [oo] WARNING: norm_correction= 137.43 for particle 130397 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 481.131 for particle 537947 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 78.4926 for particle 449008 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 33.6234 for particle 438626 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 3141.89 for particle 537978 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 19.7518 for particle 537112 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 78.7449 for particle 435839 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 1738.14 for particle 611266 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 1241.69 for particle 547753 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 11.1501 for particle 296215 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 36.4855 for particle 536632 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 1804.01 for particle 611223 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 610.097 for particle 141319 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 102.864 for particle 161938 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 28.5128 for particle 503971 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 28.2225 for particle 503997 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 18.5867 for particle 259648 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 9382.02 for particle 162827 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 29.0574 for particle 11364 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 46.6084 for particle 542922 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 9428.46 for particle 546874 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 9392.45 for particle 218112 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 21.7184 for particle 565747 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 10.5621 for particle 560397 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 14.9047 for particle 330692 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 114.2 for particle 446753 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 248.162 for particle 544157 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
 WARNING: norm_correction= 61.9979 for particle 391453 in group 1; Are your groups large enough? Or is the reference on the correct greyscale?
2.43/2.43 min ............................................................~~(,_,">
 Maximization ...
   0/   0 sec ............~~(,_,">
 RELION version: 4.0-beta-2
 exiting with an error ...==================
```
[error-report-2D.txt](https://github.com/3dem/relion/files/7997154/error-report-2D.txt)
[error-report-3D.txt](https://github.com/3dem/relion/files/7997155/error-report-3D.txt)

**Comment by biochem-fan** [comment] 2022-02-03 23:12
This is probably caused by *VERY* bad particles. Don't you have hot pixels in the movies? If so, try `Stddev for white dust removal` in the Extraction job.

Are the class averages and reconstructions affected? If so, you should remove the particles mentioned in the message. Otherwise, you can ignore the warnings.

As I mentioned in another issue, RELION 4.0 uses fewer particles and only one group to estimate the noise level in the input. This might have made the program more sensitive to outliers.

**Comment by N-Bogdanovic-85** [comment] 2022-02-04 00:06
I saw several classes that could potentially contain bad particles. When I narrow my choice to only obviously good classes, this does not happen, but I am loosing around 200 k ptcls, so I am looking to balance it out. My 3d reconstructions are severely affected as the resoultion is stuck at 21 A, as shown in the above .txt file. I am now trying your suggestion (value set to 5, Relion manual) and will update after the job runs. Thank you for the reply.

**Comment by N-Bogdanovic-85** [comment] 2022-02-04 21:02
Hello, I managed to extract the particles with the `Stddev for white dust removal 5` and the subsequent 2D classification run without the --dont_check_norm flag. However, when I run the subsequent 3D refinement, after about 17 iterations, the resolution is not improving beyond 9.0 A, but it starts getting worse and the job fails. I am including the full job log and the error log of this 3D refinement job. I know we mentioned some bad particles in the dataset. What would be the best way to filter them, since the visual inspection of 2D classes does not help much here? 

[run.err.txt](https://github.com/3dem/relion/files/8006216/run.err.txt)
[run.out.txt](https://github.com/3dem/relion/files/8006217/run.out.txt)

**Comment by biochem-fan** [comment] 2022-02-04 23:55
You said you didn't have this problem in RELION 3.1. What is the resolution from it?

Do you see artifacts (e.g. streaks) in the reconstruction?

How did you make the initial model? Is it from this dataset, or from previous datasets? Did you specify the gray scale is NOT correct?

**Comment by N-Bogdanovic-85** [comment] 2022-02-05 01:10
The dataset in relion 3.1 is different, but same protein, same data collection conditions, pretty much same workflow, except for this time I decided to try relion 4 since I have more movies/particles. The 3D reconstruction job fails as shown in the error files so I do not get a final volume. The volumes I do get, look more like the reference I provided just lower res, which is expected, considering its the same protein complex. The references come from the previous data set. I tried full-res map as reference, (3.5 A) as well as low-passing it to the 30 A in relion_image_handler. For both tries, I made a corresponding solvent masks, with softpading and expansion of 10 pix each. In this 3D refinement job we're discussing, the option "Ref map is on absolute grayscale?" I set to "yes". Please let me know if you have any ideas what might be the problem. Also, as I am in the rush to process this, I have started a new workflow in Relion 3.1 and I will import the selected particles from Relion 4.0. If the optics groups are the same, it should not be a problem?

Thank You very much.

Best regards

**Comment by biochem-fan** [comment] 2022-02-05 09:59
> The dataset in relion 3.1 is different, but same protein, same data collection conditions, pretty much same workflow

Then we cannot be sure if RELION 4.0 is wrong or this dataset is somehow worse.

>  In this 3D refinement job we're discussing, the option "Ref map is on absolute grayscale?" I set to "yes".

You should say "No" because your reference is from a different dataset.
Saying No to this is always safe.

> Please let me know if you have any ideas what might be the problem. Also, as I am in the rush to process this, I have started a new workflow in Relion 3.1 and I will import the selected particles from Relion 4.0. If the optics groups are the same, it should not be a problem?

Probably but I cannot guarantee.

**Comment by biochem-fan** [comment] 2022-02-05 23:04
There are many possibilities.

e.g.

- you put wrong dose and killed the particles
- you put a wrong objective aperture and removed all high-res information

In any case, this is your dataset issue, not RELION's, since another program also had difficulties. I close this issue. If you need further advice, please post to CCPEM.

**Closed by biochem-fan** 2022-02-05 23:04 UTC
