### ISSUE TITLE
Builds on Ubuntu Bionic (gcc@7.5.0) Fail Due to Link Order

### ISSUE THREAD

**Issue by bollig** [3dem/relion#731] opened 2021-02-09 01:05 UTC
Building relion@3.1.1 on ubuntu18.04 with gcc@7.5.0. Enabled options: MKLFFT=on, DoubleCPU=ON, CUDA=Off. 

Build fails with: 

```
[ 61%] Linking CXX executable ../../bin/relion_star_handler
cd /tmp/ubuntu/spack-stage/spack-stage-relion-3.1.1-walxkdxa77vholpzwnmc4cfodqcyi5ls/spack-build-walxkdx/src/apps && /shared/spack-0.16/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.5.0/cmake-3.13.5-kfs37giuvmqvbfjo7h435jw7sr7pruqd/bin/cmake -E cmake_link_script CMakeFiles/star_handler.dir/link.txt --verbose=1
/shared/spack-0.16/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.5.0/openmpi-4.1.0-yl7djmuebr4myldcpfwwp6k6xemxahzq/bin/mpicxx  -g -fopenmp -std=c++0x -O2 -g -DNDEBUG   -lmkl_intel_ilp64 -lmkl_core -lmkl_sequential   -rdynamic CMakeFiles/star_handler.dir/star_handler.cpp.o  -o ../../bin/relion_star_handler  -L/shared/spack-0.16/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.5.0/intel-tbb-2020.3-gavizbjesthdfklqdlljfyo4bfikov4q/lib -Wl,-rpath,/shared/spack-0.16/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.5.0/openmpi-4.1.0-yl7djmuebr4myldcpfwwp6k6xemxahzq/lib:/shared/spack-0.16/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.5.0/intel-tbb-2020.3-gavizbjesthdfklqdlljfyo4bfikov4q/lib:/shared/spack-0.16/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.5.0/libtiff-4.1.0-x23fnrn2vkf723q2hejzvj4jfd7s5dyp/lib:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: ../../lib/librelion_lib.a /shared/spack-0.16/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.5.0/openmpi-4.1.0-yl7djmuebr4myldcpfwwp6k6xemxahzq/lib/libmpi.so -ldl -ltbb_debug /shared/spack-0.16/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.5.0/libtiff-4.1.0-x23fnrn2vkf723q2hejzvj4jfd7s5dyp/lib/libtiff.so -lpng
../../lib/librelion_lib.a(image.cpp.o): In function `rewindow(Image<double>&, int)':
/tmp/ubuntu/spack-stage/spack-stage-relion-3.1.1-walxkdxa77vholpzwnmc4cfodqcyi5ls/spack-src/src/multidim_array.h:772: undefined reference to `fftw_free'
/tmp/ubuntu/spack-stage/spack-stage-relion-3.1.1-walxkdxa77vholpzwnmc4cfodqcyi5ls/spack-src/src/multidim_array.h:1146: undefined reference to `fftw_malloc'
/tmp/ubuntu/spack-stage/spack-stage-relion-3.1.1-walxkdxa77vholpzwnmc4cfodqcyi5ls/spack-src/src/multidim_array.h:772: undefined reference to `fftw_free'
/tmp/ubuntu/spack-stage/spack-stage-relion-3.1.1-walxkdxa77vholpzwnmc4cfodqcyi5ls/spack-src/src/multidim_array.h:772: undefined reference to `fftw_free'
/tmp/ubuntu/spack-stage/spack-stage-relion-3.1.1-walxkdxa77vholpzwnmc4cfodqcyi5ls/spack-src/src/multidim_array.h:1146: undefined reference to `fftw_malloc'
/tmp/ubuntu/spack-stage/spack-stage-relion-3.1.1-walxkdxa77vholpzwnmc4cfodqcyi5ls/spack-src/src/multidim_array.h:772: undefined reference to `fftw_free'
../../lib/librelion_lib.a(tilt_helper.cpp.o): In function `BasisOptimisation::deallocateTempStorage(void*) const':
/tmp/ubuntu/spack-stage/spack-stage-relion-3.1.1-walxkdxa77vholpzwnmc4cfodqcyi5ls/spack-src/src/multidim_array.h:772: undefined reference to `fftw_free'
/tmp/ubuntu/spack-stage/spack-stage-relion-3.1.1-walxkdxa77vholpzwnmc4cfodqcyi5ls/spack-src/src/multidim_array.h:772: undefined reference to `fftw_free'
../../lib/librelion_lib.a(tilt_helper.cpp.o): In function `AnisoBasisOptimisation::deallocateTempStorage(void*) const':
/tmp/ubuntu/spack-stage/spack-stage-relion-3.1.1-walxkdxa77vholpzwnmc4cfodqcyi5ls/spack-src/src/multidim_array.h:772: undefined reference to `fftw_free'
/tmp/ubuntu/spack-stage/spack-stage-relion-3.1.1-walxkdxa77vholpzwnmc4cfodqcyi5ls/spack-src/src/multidim_array.h:772: undefined reference to `fftw_free'
../../lib/librelion_lib.a(tilt_helper.cpp.o):/tmp/ubuntu/spack-stage/spack-stage-relion-3.1.1-walxkdxa77vholpzwnmc4cfodqcyi5ls/spack-src/src/multidim_array.h:772: more undefined references to `fftw_free' follow
../../lib/librelion_lib.a(tilt_helper.cpp.o): In function `TiltHelper::computeEvenZernike(int, double, Matrix2D<double> const&, int)':
/tmp/ubuntu/spack-stage/spack-stage-relion-3.1.1-walxkdxa77vholpzwnmc4cfodqcyi5ls/spack-src/src/multidim_array.h:1146: undefined reference to `fftw_malloc'
```

The same configuration on Amazon Linux 2 (gcc@7.3.1.) builds cleanly. The difference is the link order for the MKL libraries. In the case of Ubuntu, the `  -lmkl_intel_ilp64 -lmkl_core -lmkl_sequential ` appear early in the link line. If moved to the end of the link line, the build succeeds.

**Comment by biochem-fan** [comment] 2021-02-09 10:46
Thank you very much for your contribution.

- Please rebase your patch on the `ver3.1` branch, which is the latest developmental branch. 
- Do you know why Ubuntu and Amazon Linux behave differently? Is it caused by GCC (or CMake) version differences?
- Your patch duplicates MKLFFT inclusion codes in `CMakeList.txt` and `src/app/CMakeList.txt`. Do we need both?
- I am open to the use of FindMKL, if you can create a pull request for the change.

**Comment by CharlesCongdon** [comment] 2021-02-25 22:42
Evan - could you briefly switch over to the alt-cpu-2d branch and see if Jason's latest CMake changes (https://github.com/3dem/relion/commit/58bffcb52e883a0dd9a20290f1b30673cbb5d1e3) fix the link order issue in your environment?  Neither of us are CMake gurus or have AWS account, so we are not sure if this will do the trick for you, or if something like you propose is necessary.
Also, I asked around in-house, and could not find anyone who knew of a FindMKL.cmake we might be able to include to solve this as third alternative.
Thanks,
Charles

**Comment by CharlesCongdon** [comment] 2021-02-25 22:47
BTW, with the CMakeLists.txt in alt-cpu-2d you'll need to cmake as follows if you use the Intel Compiler:
cmake \
-DCMAKE_C_COMPILER=icc \
-DCMAKE_CXX_COMPILER=icpc \
-DMPI_C_COMPILER=mpiicc \
-DMPI_CXX_COMPILER=mpiicpc \
…..

**Comment by bollig** [comment] 2021-03-04 05:13
Ok, branch devel-altcpu-2dopt builds successfully on ubuntu1804 with gcc+intel MKL. Looks like you guys have a clean PR

**Comment by biochem-fan** [comment] 2021-03-09 15:00
@CharlesCongdon
I merged @do-jason's `devel-altcpu-2dopt` branch into `ver3.1` (not to `master` yet).

**Closed by biochem-fan** 2021-03-09 15:00 UTC
