### ISSUE TITLE
INSTALL ERROR: make[2]: *** [bin/relion_autopick_mpi] Error 1 make[1]: *** [src/apps/CMakeFiles/autopick.dir/all] Error 2 #480

### ISSUE THREAD

**Issue by ryanlindsay** [3dem/relion#568] opened 2020-01-21 06:06 UTC
Trying to compile on Redhat 7 with GCC 7.3 and Cuda 10.1
cmake completes
cmake -DCUDA_ARCH=60 ..
-- BUILD TYPE set to the default type:  'Release'
-- Using provided CUDA_ARCH=60
-- ALLOW_CTF_IN_SAGD enabled - This build of RELION allows modulation of particle images by a contrast transfer function inside stochastic average gradient descent, as specified in        Claim 1 of patent US10,282,513B2
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- MPI_INCLUDE_PATH : /usr/include/c++/4.8.2/backward;/cm/shared/apps/mpich/ge/gcc/64/3.2.1/include
-- MPI_LIBRARIES : /cm/shared/apps/mpich/ge/gcc/64/3.2.1/lib/libmpicxx.so;/cm/shared/apps/mpich/ge/gcc/64/3.2.1/lib/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /usr/include/c++/4.8.2/backward;/cm/shared/apps/mpich/ge/gcc/64/3.2.1/include
-- MPI_CXX_LIBRARIES : /cm/shared/apps/mpich/ge/gcc/64/3.2.1/lib/libmpicxx.so;/cm/shared/apps/mpich/ge/gcc/64/3.2.1/lib/libmpi.so
-- CMAKE_C_COMPILER : /usr/bin/cc
-- CMAKE_CXX_COMPILER : /usr/bin/c++
-- MPI_C_COMPILER : /cm/shared/apps/mpich/ge/gcc/64/3.2.1/bin/mpicc
-- MPI_CXX_COMPILER : /cm/shared/apps/mpich/ge/gcc/64/3.2.1/bin/mpicxx
-- CMAKE_CXX_COMPILER_ID : GNU
-- CMAKE_C_COMPILER : /cm/shared/apps/mpich/ge/gcc/64/3.2.1/bin/mpicc
-- CMAKE_CXX_COMPILER : /cm/shared/apps/mpich/ge/gcc/64/3.2.1/bin/mpicxx
-- MPI_C_COMPILER : /cm/shared/apps/mpich/ge/gcc/64/3.2.1/bin/mpicc
-- MPI_CXX_COMPILER : /cm/shared/apps/mpich/ge/gcc/64/3.2.1/bin/mpicxx
-- Could NOT find FLTK (missing:  FLTK_LIBRARIES FLTK_FLUID_EXECUTABLE)
-- No FLTK installation was found
-- Found previously built non-system FLTK libraries that will be used.
-- FLTK_INCLUDE_DIR: /home/xxxx/relion/external/fltk/include
-- FLTK_LIBRARIES:   /home/xxxx/relion/external/fltk/lib/libfltk.so
-- Single-precision FFTW was required but NOT found
-- Double-precision FFTW was required but NOT found
-- Found previously built non-system single precision FFTW libraries that will be used.
-- Found previously built non-system double precision FFTW libraries that will be used.
BUILD_SHARED_LIBS = OFF
-- Building static libs (larger build size and binaries)
Running apps/CMakeLists.txt...
-- CMAKE_BINARY_DIR:/home/xxxx/relion/build
-- Git commit ID: 06afb9fe634d32265ce9e305e655e30812057683
TIFF FOUND
PNG FOUND
OPENMP FOUND
-- Configuring done
-- Generating done

However when I try 
make -j 4 
I get 
Invoking recipe from src/apps/CMakeFiles/autopick.dir/build.make:103 to update target `bin/relion_autopick'.
Putting child 0x676d30 (bin/relion_autopick) PID 69952 on the chain.
  Recipe of `bin/relion_autopick' is being run.
 Finished prerequisites of target file `src/apps/CMakeFiles/autopick.dir/build'.
The prerequisites of `src/apps/CMakeFiles/autopick.dir/build' are being made.
Live child 0x676d30 (bin/relion_autopick) PID 69952
Linking CXX executable ../../bin/relion_autopick_mpi
Reaping winning child 0x67b360 PID 69951
Live child 0x67b360 (bin/relion_autopick_mpi) PID 69953
Linking CXX executable ../../bin/relion_autopick
Reaping winning child 0x676d30 PID 69952
Live child 0x676d30 (bin/relion_autopick) PID 69955
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `LaunchHandleError(cudaError, char const*, int)':
tmpxft_00010fa3_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0x97): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `HandleError(cudaError, char const*, int)':
tmpxft_00010fa3_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0x1bf): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `LaunchHandleError(cudaError, char const*, int) [clone .constprop.187]':
tmpxft_00010fa3_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0x4fd): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function .`HandleError(cudaError, char const*,. int) [clone .constprop.188]':
tmpxft_00010fa3_00000000/-5_cuda_autopicker.cudafe1.cpp..:(.text+0x615/lib): undefined /reference to `RelionError::RelionErrorlibrelion_gpu_util.a(std:(:string const&, stdrelion_gpu_util_generated_cuda_autopicker.cu.o::string )const&:, long)'
 ../In.. /lib/librelion_gpu_util.a(functionrelion_gpu_util_generated_cuda_autopicker.cu.o): In ` function `void runCenterFFT<float>(AccPtr<LaunchHandleErrorfloat>&, int, int, bool, int) [clone .constprop.176]':
(tmpxft_00010fa3_00000000-5_cuda_autopicker.cudafe1.cppcudaError:(.text+0x7b9,): undefined reference to ` RelionError::charRelionError(std const::string const&, std::string const&, long)'
.*./../lib, /librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o):tmpxft_00010fa3_00000000-5_cuda_autopicker.cudafe1.cppint:(.text+0xba4): more undefined )references to `RelionError::'RelionError(std:::string const&, std::string
 const&,tmpxft_00010fa3_00000000- long)' 5_cuda_autopicker.cudafe1.cppfollow
:..(./..text+/lib0x97/librelion_gpu_util.a()relion_gpu_util_generated_cuda_autopicker.cu.o): In: function  `MultidimArrayundefined <double>::resizereference(long , long, tolong,  `long) RelionError[clone: .constprop.177:]'RelionError:
tmpxft_00010fa3_00000000-(std5_cuda_autopicker.cudafe1.cpp:(.text+:0xc4c):: undefined reference to `FileName::addExtensionstring(std ::string const&) const'
tmpxft_00010fa3_00000000-const5_cuda_autopicker.cudafe1.cpp:&(.text+0xd75): undefined ,reference to ` RelionError::stdRelionError(std::string const&, std::string const&, long:)'
tmpxft_00010fa3_00000000-5_cuda_autopicker.cudafe1.cpp:(.text:+0xe40)string: undefined reference  to `RelionError::RelionErrorconst(std::string &const&,, std::string  const&long), 'long)'
tmpxft_00010fa3_00000000-5_cuda_autopicker.cudafe1.cpp:(
.text+0xed8): undefined reference to `.RelionError::RelionError(std.::/string const&., std::string const&, .long)'
../../lib/librelion_gpu_util.a/(relion_gpu_util_generated_cuda_autopicker.cu.olib): In function /`AutoPickerCuda::calculateStddevAndMeanUnderMasklibrelion_gpu_util.a(AccPtr<float2>&, (relion_gpu_util_generated_cuda_autopicker.cu.oAccPtr<float2>)&,:  AccPtr<float2>&, int, AccPtrIn<float >&function, AccPtr< float>&`, HandleErrorunsigned (long, unsigned long, unsigned long,cudaError, unsigned long)' :
Invoking recipe from src/apps/CMakeFiles/autopick.dir/build.make:103 to update target `bin/relion_autopick'.
Putting child 0x676d30 (bin/relion_autopick) PID 69952 on the chain.
  Recipe of `bin/relion_autopick' is being run.
 Finished prerequisites of target file `src/apps/CMakeFiles/autopick.dir/build'.
The prerequisites of `src/apps/CMakeFiles/autopick.dir/build' are being made.
Live child 0x676d30 (bin/relion_autopick) PID 69952
Linking CXX executable ../../bin/relion_autopick_mpi
Reaping winning child 0x67b360 PID 69951
Live child 0x67b360 (bin/relion_autopick_mpi) PID 69953
Linking CXX executable ../../bin/relion_autopick
Reaping winning child 0x676d30 PID 69952
Live child 0x676d30 (bin/relion_autopick) PID 69955
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `LaunchHandleError(cudaError, char const*, int)':
tmpxft_00010fa3_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0x97): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `HandleError(cudaError, char const*, int)':
tmpxft_00010fa3_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0x1bf): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `LaunchHandleError(cudaError, char const*, int) [clone .constprop.187]':
tmpxft_00010fa3_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0x4fd): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function .`HandleError(cudaError, char const*,. int) [clone .constprop.188]':
tmpxft_00010fa3_00000000/-5_cuda_autopicker.cudafe1.cpp..:(.text+0x615/lib): undefined /reference to `RelionError::RelionErrorlibrelion_gpu_util.a(std:(:string const&, stdrelion_gpu_util_generated_cuda_autopicker.cu.o::string )const&:, long)'
 ../In.. /lib/librelion_gpu_util.a(functionrelion_gpu_util_generated_cuda_autopicker.cu.o): In ` function `void runCenterFFT<float>(AccPtr<LaunchHandleErrorfloat>&, int, int, bool, int) [clone .constprop.176]':
(tmpxft_00010fa3_00000000-5_cuda_autopicker.cudafe1.cppcudaError:(.text+0x7b9,): undefined reference to ` RelionError::charRelionError(std const::string const&, std::string const&, long)'
.*./../lib, /librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o):tmpxft_00010fa3_00000000-5_cuda_autopicker.cudafe1.cppint:(.text+0xba4): more undefined )references to `RelionError::'RelionError(std:::string const&, std::string
 const&,tmpxft_00010fa3_00000000- long)' 5_cuda_autopicker.cudafe1.cppfollow
:..(./..text+/lib0x97/librelion_gpu_util.a()relion_gpu_util_generated_cuda_autopicker.cu.o): In: function  `MultidimArrayundefined <double>::resizereference(long , long, tolong,  `long) RelionError[clone: .constprop.177:]'RelionError:
tmpxft_00010fa3_00000000-(std5_cuda_autopicker.cudafe1.cpp:(.text+:0xc4c):: undefined reference to `FileName::addExtensionstring(std ::string const&) const'
tmpxft_00010fa3_00000000-const5_cuda_autopicker.cudafe1.cpp:&(.text+0xd75): undefined ,reference to ` RelionError::stdRelionError(std::string const&, std::string const&, long:)'
tmpxft_00010fa3_00000000-5_cuda_autopicker.cudafe1.cpp:(.text:+0xe40)string: undefined reference  to `RelionError::RelionErrorconst(std::string &const&,, std::string  const&long), 'long)'
tmpxft_00010fa3_00000000-5_cuda_autopicker.cudafe1.cpp:(
.text+0xed8): undefined reference to `.RelionError::RelionError(std.::/string const&., std::string const&, .long)'
../../lib/librelion_gpu_util.a/(relion_gpu_util_generated_cuda_autopicker.cu.olib): In function /`AutoPickerCuda::calculateStddevAndMeanUnderMasklibrelion_gpu_util.a(AccPtr<float2>&, (relion_gpu_util_generated_cuda_autopicker.cu.oAccPtr<float2>)&,:  AccPtr<float2>&, int, AccPtrIn<float >&function, AccPtr< float>&`, HandleErrorunsigned (long, unsigned long, unsigned long,cudaError, unsigned long)' :
 

There's a lot more error there. But it doesn't seem to like linking that relion_autopick_mpi file
Since cmake seems to be happy, I'm not sure where else to look

**Comment by biochem-fan** [comment] 2020-01-28 10:28
Duplicate of #569.

**Closed by biochem-fan** 2020-01-28 10:28 UTC
