### ISSUE TITLE
ERROR: tomogramTable for Position_44 does not contain a rlnTomoMicrographNameEven label

### ISSUE THREAD

**Issue by xingxingjiukunkun** [3dem/relion#1176] opened 2024-08-22 06:50 UTC
i don't know what problem happen ,can anyone help me

in: /public/apps/em/relion-5.0/relion/src/jaz/tomography/tomogram_set.cpp, line 228
ERROR: 
ERROR: tomogramTable for Position_16 does not contain a rlnTomoMicrographNameEven label
in: /public/apps/em/relion-5.0/relion/src/jaz/tomography/tomogram_set.cpp, line 228
ERROR: 
ERROR: tomogramTable for Position_34 does not contain a rlnTomoMicrographNameEven label
000/??? sec ~~(,_,">                                                          [oo]in: /public/apps/em/relion-5.0/relion/src/jaz/tomography/tomogram_set.cpp, line 228
ERROR: 
ERROR: tomogramTable for Position_11 does not contain a rlnTomoMicrographNameEven label
in: /public/apps/em/relion-5.0/relion/src/jaz/tomography/tomogram_set.cpp, line 228
ERROR: 
ERROR: tomogramTable for Position_27 does not contain a rlnTomoMicrographNameEven label
in: /public/apps/em/relion-5.0/relion/src/jaz/tomography/tomogram_set.cpp, line 228
ERROR: 
ERROR: tomogramTable for Position_65 does not contain a rlnTomoMicrographNameEven label
in: /public/apps/em/relion-5.0/relion/src/jaz/tomography/tomogram_set.cpp, line 228
ERROR: 
ERROR: tomogramTable for Position_22 does not contain a rlnTomoMicrographNameEven label
in: /public/apps/em/relion-5.0/relion/src/jaz/tomography/tomogram_set.cpp, line 228
ERROR: 
ERROR: tomogramTable for Position_44 does not contain a rlnTomoMicrographNameEven label
in: /public/apps/em/relion-5.0/relion/src/jaz/tomography/tomogram_set.cpp, line 228
ERROR: 
ERROR: tomogramTable for Position_53_2 does not contain a rlnTomoMicrographNameEven label
--------------------------------------------------------------------------
prterun detected that one or more processes exited with non-zero status,
thus causing the job to be terminated. The first process to do so was:

   Process name: [prterun-gpu2-583311@1,3] Exit code:    1

**Comment by biochem-fan** [comment] 2024-08-22 06:56
This is a duplicate of https://github.com/3dem/relion/issues/1158. If the solution there does not solve your problem, please reopen this issue.

**Closed by biochem-fan** 2024-08-22 06:56 UTC
