### ISSUE TITLE
cannot read externally prepared .mrcs or its star file

### ISSUE THREAD

**Issue by psryubh** [3dem/relion#288] opened 2017-09-22 02:40 UTC
This is my first time to try negative stain data.
As the wiki says, I prepared the phase-flipped particles from EMAN2.12.
And then I converted .hdf stack files to .mrcs files.
Afterward, I used relion_preprocess command like the following,
`relion_preprocess --operate_on ???.mrcs --operate_out ???_norm.mrcs --norm true --bg_radius 32`
, and I imported the generated .star file from the above.

But when I tried to display the file using "subset selection", the following error came up.

ERROR: 
Cannot read file 13_norm.mrcs It does not exist
File: /home/bumhan/repo_relion2.1b_fix/relion/src/image.h line: 163

When I tried to import a few .mrcs with node type=2D reference, the same error was shown.
(.star file from the mrcs files could be imported but further processes were impossible with this)

Even simple Display function in the menu did not respond when I opened that mrcs file.

Am I missing something? or is this inevitable error?

Han

**Comment by biochem-fan** [comment] 2017-09-22 05:58
Hi, 

I encountered the same bug yesterday. The problem is that while the written `???_norm.star` referres to `???_norm.mrcs`, the program writes `???_norm.mrcs.mrcs`. 

This bug has been fixed in the (internal) development version. Meanwhile, renaming the output solves the problem.

**Comment by psryubh** [comment] 2017-09-22 06:23
Thanks! I will try!

Best,




Bum Han Ryu

Ph.D student (Combined)
Structural Biology LAB.,
Dept. of Molecular Cell Biology, Sungkyunkwan University School of Medicine,
Suwon, South Korea

**Comment by psryubh** [comment] 2017-09-27 05:56
I found the potential reason why sometime any type of data cannot be read in relion. In this case, there is no job_pipeliner generated. I think some warnings occurred in installation may be related to this. Plus, I guess almost all issues about "Cannot read file ~ It does not exist" may be the same cases. Is there any way to solve out this problem?

**Closed** 2019-02-25 13:57 UTC
