### ISSUE TITLE
relion 3 compiled sucessfully with CUDA or ALTCPU but no GUI and no error message 

### ISSUE THREAD

**Issue by riverseow** [3dem/relion#453] opened 2019-03-12 23:37 UTC
I am trying to get the latest relion working on a workstation with Ubuntu 18.10 and Geforce 1080 Ti graphic card. I had an old Relion 1.3 works fine. Now when I compiled the latest Relion 3.0. I first tried CUDA 10.1. Everything seems fine but after compile and install, when I execute relion, no GUI display, one relion process using 100% of the CPU. No crashes, after answer "y" to the question about start a new project here, nothing display. I thought maybe it is CUDA. I tested CUDA compiler using CUDA's samples and everything runs fine.  Then I did a new compilation of Relion 3.0 with -DALTCPU under a new directory. Everything looks fine and again, after typing relion, no GUI, no error message. 

Any hints to solve the problem will be appreciated. Should I downgrade to CUDA 9 and install GCC 6.0. I installed CUDA10.1 because using previous CUDA, it complains that current GCC 8.2 cannot compile the CUDA. 

River

**Comment by bforsbe** [comment] 2019-03-13 07:50
Are you launching relion as a background process?

**Comment by riverseow** [comment] 2019-03-13 17:51
No. I just type "relion" and enter, no "&" after the command. In previous version, this should bring up the GUI but I see nothing but only 100% for 1 cpu is running for ever. Some lock file and default_pipeline.star file were written but no other messages or anything. I don't have anyway to find out what is the problem. Is there any debug mode to print to standout for relion to let me find out what step got hold for ever.

**Comment by bforsbe** [comment] 2019-03-14 08:12
if you compile using cmake flags 

´´´ -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_SHARED_LIBS=OFF ´´´

you can run relion through gdb and find out where it is catching. Using your debug-binary, run 

´´´ gdb --args relion ´´´

and hit 'r' to run it. If it seems stalled, stop it through ctrl+c and ask for a backtrace by typing 'bt' and hit enter.

**Comment by riverseow** [comment] 2019-03-14 22:44
Bjorn,

Thank you so much. I followed your instructions. First, I got an error
message "cannot open display on localhost:0.0". Instead of running directly
from the ubuntu terminal. I started an Xterm which make sure to start X
Windows OK and now it seems OK. I got the GUI. No more other errors.  I
thought that was the problem. However, when I compiled again without those
debug modes, I still cannot get the GUI with xterm. I thought maybe the
BUILD_SHARED_LIB=OFF is enough. I compiled with that flag only, still
not working. I must compiled with both debug flag and I can get GUI without
any error message. I still get no clue what is problem. At least now, I
have a version that I can get GUI. Will compiling with the debug mode slow
down the program a lot? Maybe some of the default optimization flags lead
to this problem?

River

**Comment by Fravadona** [comment] 2019-03-25 17:48
What's the output of `ldd <Relion install dir>/bin/relion` ?

**Comment by riverseow** [comment] 2019-04-07 06:42
Sorry to be slow: See below:
relion/bin>ldd relion
        linux-vdso.so.1 (0x00007ffc539eb000)
        libfltk.so.1.3 => /usr/lib/x86_64-linux-gnu/libfltk.so.1.3 (0x00001518342df000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00001518342be000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x0000151834134000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x0000151833fa7000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x0000151833f8d000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x0000151833da3000)
        libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x0000151833b97000)
        libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x000015183398d000)
        libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x0000151833787000)
        libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x0000151833575000)
        libXft.so.2 => /usr/lib/x86_64-linux-gnu/libXft.so.2 (0x000015183335f000)
        libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x000015183331a000)
        libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x0000151833313000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x000015183330d000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00001518331d3000)
        /lib64/ld-linux-x86-64.so.2 (0x000015183488a000)
        libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x0000151832f1f000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x0000151832ee2000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x0000151832ed7000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x0000151832eae000)
        libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x0000151832c7c000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x0000151832a5f000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x000015183285b000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x0000151832653000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x000015183243c000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x0000151832432000)

**Comment by kmlyn** [comment] 2019-04-25 22:21
I had the same issue with GCC-8.2. I tracked it down to missing return statement in `bool MetaDataTable::getValueToString()` function present in `src/metadata_table.cpp`. There are more problems of the same kind in the code. 
The compiler's behaviour is intended and explained [here](https://gcc.gnu.org/gcc-8/porting_to.html):

> ### `-Wreturn-type` is enabled by default
> 
> G++ now assumes that control never reaches the end of a non-void function (i.e. without reaching a return statement). This means that you should always pay attention to -Wreturn-type warnings, as they indicate code that can misbehave when optimized.

**Comment by biochem-fan** [comment] 2019-04-25 22:39
Thank you very much for pointing this out. I will investigate this issue.

**Comment by biochem-fan** [comment] 2019-04-26 10:36
We are testing a fix at LMB now. Once confirmed, I will push it to here.

**Comment by biochem-fan** [comment] 2019-05-07 11:14
Fixed in 3.0.5.

**Closed by biochem-fan** 2019-05-07 11:14 UTC
Labels: bug
