### ISSUE TITLE
no output .star files from particles picking

### ISSUE THREAD

**Issue by cdegut** [3dem/relion#999] opened 2023-10-27 13:22 UTC
RELION version 5.0-beta0
Both autopicking and manual picking jobs do not seem to generate an output .star file that can be read by extract.
Tested on two diferent datasets.

**Comment by biochem-fan** [comment] 2023-11-10 07:45
I cannot reproduce your problem. Perhaps an installation problem?

**Comment by kcf26** [comment] 2023-11-22 18:33
I'm having the same issue. Autopick runs and generates star files for each micrograph in the Micrograph folder, but no output.star file to input into an extract job. Trying to figure out a way to work around this...

**Comment by kcf26** [comment] 2023-11-22 18:44
> I'm having the same issue. Autopick runs and generates star files for each micrograph in the Micrograph folder, but no output.star file to input into an extract job. Trying to figure out a way to work around this...

A workaround that seems to be working is to manually create a coords_suffix_autopick.star file in your autopick job directory which lists the path to the micrographs picked from (e.g. 'Select/job004/micrographs.star'), and using this file as an input to an Extract job.

**Comment by biochem-fan** [comment] 2023-11-22 23:50
Are you sure you're `PATH` is properly set? It is possible that you are running RELION 5.0 GUI but an older version of `relion_*` for actual jobs.

**Comment by kcf26** [comment] 2023-11-23 02:58
> Are you sure you're `PATH` is properly set? It is possible that you are running RELION 5.0 GUI but an older version of `relion_*` for actual jobs.

I checked my path and it is pointing to the relion 5.0 install (I'm also able to run the VDAM algorithm in 2D classification without error through this GUI, which I don't think would work if the GUI wasn't connected to the right install. The only other relion install I have on this workstation is relion 3.1, which didn't utilize the VDAM algorithm).

**Comment by kcf26** [comment] 2023-11-23 18:38
> Are you sure you're `PATH` is properly set? It is possible that you are running RELION 5.0 GUI but an older version of `relion_*` for actual jobs.

You are absolutely right, as usual biochem-fan. I was trying to call my new relion install by pointing to it's absolute path instead of correctly modifying my .bashrc file. which relion was still giving the location of relion 3.1.

**Comment by biochem-fan** [comment] 2023-11-23 23:36
@kcf26 Great.

I close this issue. @cdegut, please reopen this issue if your problem is not the case.

**Closed by biochem-fan** 2023-11-23 23:36 UTC
