### ISSUE TITLE
Relion 2.1 2D Classification failed with CPU

### ISSUE THREAD

**Issue by fangdazhuzhu** [3dem/relion#337] opened 2018-01-31 07:13 UTC
I start the relion with the following command:mpiexec -np 2 relion_refine_mpi  --o Class2D/job007/ --i particles.star --ctf --iter 1 --tau2_fudge 2 --particle_diameter 150 --K 100 --flatten_solvent --zero_mask --strict_highres_exp 8 --oversampling 1 --psi_step 12 --offset_range 5 --offset_step 2 --norm --scale

 === RELION MPI setup ===-oversampling 1 --psi_step 12 --offset_rang
 + Number of MPI processes             = 2
 + Master  (0) runs on host            = asc001
 + Slave     1 runs on host            = asc001
 =================
 Running CPU instructions in double precision. 
 Estimating initial noise spectra 
2.10/2.10 min ............................................................~~(,_,">
  1: MPI_ERR_TYPE: invalid datatype
  1: MPI_ERR_TYPE: invalid datatype
terminate called after throwing an instance of 'RelionError'
[asc001:05736] *** Process received signal ***
[asc001:05736] Signal: Aborted (6)
[asc001:05736] Signal code:  (-6)
[asc001:05736] [ 0] /lib64/libpthread.so.0(+0xf5e0)[0x7f36ce6445e0]
[asc001:05736] [ 1] /lib64/libc.so.6(gsignal+0x37)[0x7f36ce2a71f7]
[asc001:05736] [ 2] /lib64/libc.so.6(abort+0x148)[0x7f36ce2a88e8]
[asc001:05736] [ 3] /lib64/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x165)[0x7f36cedc9ac5]
[asc001:05736] [ 4] /lib64/libstdc++.so.6(+0x5ea36)[0x7f36cedc7a36]
[asc001:05736] [ 5] /lib64/libstdc++.so.6(+0x5ea63)[0x7f36cedc7a63]
[asc001:05736] [ 6] /lib64/libstdc++.so.6(+0x5ec83)[0x7f36cedc7c83]
[asc001:05736] [ 7] /home/newidea/environment_install/relion-2.1/install_dir/lib/librelion_lib.so(_ZN7MpiNode16report_MPI_ERROREi+0x119)[0x7f36cfb5e3a9]
[asc001:05736] *** End of error message ***
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 1 with PID 0 on node asc001 exited on signal 6 (Aborted).
--------------------------------------------------------------------------
thanks a lot .

**Comment by bforsbe** [comment] 2018-02-01 00:55
Duplicate of #234

**Closed by bforsbe** 2018-02-01 00:55 UTC
