### ISSUE TITLE
relion_mask_create issue with small mrc

### ISSUE THREAD

**Issue by olibclarke** [3dem/relion#294] opened 2017-10-05 16:06 UTC
Hi,

I have an mrc  generated using molmap in Chimera, and I'd like to create a mask from it in relion.

I run: 
`relion_mask_create --i molmap.mrc --o res_measure_mask.mrc --ini_threshold 0.001 --width_soft_edge 6 --extend_inimask 6 >& mask5.log &`

..and the mask that comes out the other end is blank, all zeroes, despite the fact that the ini_threshold should enclose a substantial volume, based on inspection in Chimera. The header of the input mrc looks fine when inspected with imod. Using an input mrc corresponding to a different, larger fragment of the same protein the resulting mask looks normal. 

Happy to provide the offending mrc offline if it is any help, I am stumped.

Cheers,
Oli.

**Comment by dkimanius** [comment] 2017-10-05 16:46
You can send me the map on dkimanius (at) gmail dot com.

**Comment by olibclarke** [comment] 2017-10-05 22:45
Thanks Dari! Sent.

Cheers
Oli

**Comment by dkimanius** [comment] 2017-10-09 11:13
Hi Oli,

Thanks for the maps. Running the provided command with relion 2.1.b1 and the maps I don't believe I was able to reproduce the issue. Rather I've got the expected results out, a map that encloses the region specified by the threshold with the extended voxels and a soft edge. Could you perhaps retry the command-line to make sure that you get the same results and then perhaps rebuild relion to make sure that everything there was ok. In any other case you can try instead using relion_image_handler that shares some of the functionality of relion_mask_create.

Best,
Dari

**Comment by dkimanius** [comment] 2017-10-09 15:48
Yes, this would be useful. There are a bunch of checks one would expect there to be done by the file-handler in relion that are currently missing. For instance checks for not-a-number or invalid header values, which have been an issue for some users. Ideally a checksum-value stored in the header would be very useful in this and many other cases, since it would easily enable checks for any data corruption issues that occurred during write, storage, data transfer or read. Unfortunately this is not supported by the MRC-file standard (http://bio3d.colorado.edu/imod/doc/mrc_format.txt). Considering how many different ways your data can be corrupted, just adding a check for truncated files falls far down on the priority list =) Ideally this will be addressed in the future by another effort currently under way that I wont go into here.

**Closed** 2017-10-18 09:54 UTC
